<a href="https://colab.research.google.com/github/hyuntaedo/Data_Analysis/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#<string>1. Numpy</string>


In [ ]:
import numpy as np
data = [[1,2,3.0],[4,5,6],[7,8,9]]
a = np.array(data)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a = a.astype(np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [ ]:
a[0][1]
a[0]

array([1., 2., 3.], dtype=float32)

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,13).reshape(3,2,2) #초기 종료 스택값

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
a[0][1] = np.nan

In [ ]:
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [ ]:
a = np.linspace(1,10,20) #초기 종료 몇개를 넣을지
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
a = np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
data = np.arange(1,10).reshape(3,3)

In [ ]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#<string>Matrix calculate</string>

In [ ]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
data / data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.dot(data,data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
data@data

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

#차원

In [ ]:
#0차원 : 스칼라
a = np.array(1)
a
a.shape
a.ndim

0

In [ ]:
#1차원 벡터
a = np.array([1,2,3,4,5])
a
a.shape
a.ndim

1

In [ ]:
#2차원 행렬
a = np.array([[1,2,3],[4,5,6]])
a
a.shape
a.ndim

2

In [ ]:
#3차원 이상의 다차원 행렬을 Tensor
a = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
a
a.shape
a.ndim

3

# matrix의 유형

In [ ]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
b = np.ones(12).reshape(2,3,2)
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
#0행렬
c = np.zeros(12).reshape(2,3,2)
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
#단위행열
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#내가 원하는 행렬만큼의 0행렬 생성
e = np.zeros([3,4])
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
e = np.zeros([3,4,2])
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
#0에 가까운 수가 나온다.
f = np.empty([2,3])
f

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [ ]:
g = np.full((3,4),1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [ ]:
h = np.linspace(2,10,6)
h

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

##**집계함수**

In [ ]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a[0][0] = 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [ ]:
a[0,1] =1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [ ]:
np.mean(a) #평균

114.4

In [ ]:
np.median(a) #중앙값

6.5

In [ ]:
np.std(a) #표준편차

296.5485457728633

In [ ]:
np.var(a) #분산

87941.04

In [ ]:
np.sum(a) #합계

1144

In [ ]:
np.sum(a,axis=0) #x축으로 더하기

array([ 105, 1006,    9,   11,   13])

In [ ]:
np.sum(a,axis=1) #y축으로 더하기

array([1109,   35])

In [ ]:
np.max(a) #max값

1000

In [ ]:
np.min(a) #min값

2

#<strong>2. Pandas</strong>

In [ ]:
import pandas as pd
import numpy as np
data = np.arange(0,50,10)
data

array([ 0, 10, 20, 30, 40])

In [ ]:
a = pd.Series(data,index=['a','b','c','d','e'])
a

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [ ]:
b = pd.Series(data)
b

0     0
1    10
2    20
3    30
4    40
dtype: int64

In [ ]:
a['b']

10

In [ ]:
a.loc['b'] #인덱스값

10

In [ ]:
a.iloc[1] #순서

10

In [ ]:
a + 10
a - 10
a * 10
a ** 2
a  / 5
a // 5 
a % 3

a    0
b    1
c    2
d    0
e    1
dtype: int64

In [ ]:
a[a > 15] #boolean indexing

c    20
d    30
e    40
dtype: int64

# <strong>집계함수</strong>

In [ ]:
a.add(100)

a    100
b    110
c    120
d    130
e    140
dtype: int64

In [ ]:
a.sub(100)

a   -100
b    -90
c    -80
d    -70
e    -60
dtype: int64

In [ ]:
a.mul(100)

a       0
b    1000
c    2000
d    3000
e    4000
dtype: int64

In [ ]:
a.div(100)

a    0.0
b    0.1
c    0.2
d    0.3
e    0.4
dtype: float64

In [ ]:
a.mod(100)

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [ ]:
a.min()

0

In [ ]:
a.max()

40

In [ ]:
a.sum()

100

In [ ]:
a.mean()

20.0

In [ ]:
a.median()

20.0

In [ ]:
a.std()

15.811388300841896

In [ ]:
a.var()

250.0

In [ ]:
rawData = np.random.randint(50,100,size=(4,3))
rawData

array([[70, 72, 68],
       [60, 63, 96],
       [93, 55, 58],
       [82, 64, 60]])

In [ ]:
df = pd.DataFrame(rawData,index=['1반','2반','1반','2반'],columns=['국','영','수'])
df

국   영   수
1반  70  72  68
2반  60  63  96
1반  93  55  58
2반  82  64  60

In [ ]:
df['국']

1반    70
2반    60
1반    93
2반    82
Name: 국, dtype: int64

In [ ]:
#df[0] -> Error

In [ ]:
df['평균'] = round((df['국'] + df['영'] + df['수'])/3,2)
df

국   영   수     평균
1반  70  72  68  70.00
2반  60  63  96  73.00
1반  93  55  58  68.67
2반  82  64  60  68.67

In [ ]:
df['na'] = np.nan
df

국   영   수     평균  na
1반  70  72  68  70.00 NaN
2반  60  63  96  73.00 NaN
1반  93  55  58  68.67 NaN
2반  82  64  60  68.67 NaN

In [ ]:
del df['na']
df

국   영   수     평균
1반  70  72  68  70.00
2반  60  63  96  73.00
1반  93  55  58  68.67
2반  82  64  60  68.67

In [ ]:
df[df.평균 > 70]

국   영   수    평균
2반  60  63  96  73.0

#<strong>결측값 처리</strong>

In [ ]:
df = df.astype('float64')
df

국     영     수
1반  70.0  72.0  68.0
2반  60.0  63.0  96.0
1반  93.0  55.0  58.0
2반  82.0  64.0  60.0

In [ ]:
df['수'][2] = np.nan
df

국     영     수
1반  70.0  72.0  68.0
2반  60.0  63.0  96.0
1반  93.0  55.0   NaN
2반  82.0  64.0  60.0

In [ ]:
df.dropna(axis=0) # row단위가 없어짐
df

국     영     수
1반  70.0  72.0  68.0
2반  60.0  63.0  96.0
1반  93.0  55.0   NaN
2반  82.0  64.0  60.0

In [ ]:
df.dropna(axis=1) #col단위로 사라짐

국     영
1반  70.0  72.0
2반  60.0  63.0
1반  93.0  55.0
2반  82.0  64.0

In [ ]:
df.fillna('hello')

국     영      수
1반  70.0  72.0     68
2반  60.0  63.0     96
1반  93.0  55.0  hello
2반  82.0  64.0     60

In [ ]:
df.fillna(0)

국     영     수
1반  70.0  72.0  68.0
2반  60.0  63.0  96.0
1반  93.0  55.0   0.0
2반  82.0  64.0  60.0

In [ ]:
df.fillna(df.mean())

국     영          수
1반  70.0  72.0  68.000000
2반  60.0  63.0  96.000000
1반  93.0  55.0  74.666667
2반  82.0  64.0  60.000000

#<strong>MultiIndex</strong>

In [ ]:
df

국     영     수
1반  70.0  72.0  68.0
2반  60.0  63.0  96.0
1반  93.0  55.0   NaN
2반  82.0  64.0  60.0

In [ ]:
df.T # row와 column값이 바뀐다

1반    2반    1반    2반
국  70.0  60.0  93.0  82.0
영  72.0  63.0  55.0  64.0
수  68.0  96.0   NaN  60.0

In [ ]:
df.index = [['1학년','1학년','2학년','2학년'],['1반','2반','1반','2반']]
df #multi index로 변환됨

국     영     수
1학년 1반  70.0  72.0  68.0
    2반  60.0  63.0  96.0
2학년 1반  93.0  55.0   NaN
    2반  82.0  64.0  60.0

In [ ]:
df.columns = [['언어','언어','수리'],['국','영','수']]
df

언어          수리
           국     영     수
1학년 1반  70.0  72.0  68.0
    2반  60.0  63.0  96.0
2학년 1반  93.0  55.0   NaN
    2반  82.0  64.0  60.0

In [ ]:
df['언어']['국']

1학년  1반    70.0
     2반    60.0
2학년  1반    93.0
     2반    82.0
Name: 국, dtype: float64

In [ ]:
df.iloc[0]

언어  국    70.0
    영    72.0
수리  수    68.0
Name: (1학년, 1반), dtype: float64

In [ ]:
df.loc['1학년']
df.loc['1학년'].loc['1반']

언어  국    70.0
    영    72.0
수리  수    68.0
Name: 1반, dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('1학년', '1반') to ('2학년', '2반')
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   (언어, 국)  4 non-null      float64
 1   (언어, 영)  4 non-null      float64
 2   (수리, 수)  3 non-null      float64
dtypes: float64(3)
memory usage: 328.0+ bytes


In [ ]:
df.head() #맨 처음 데이터5개

언어          수리
           국     영     수
1학년 1반  70.0  72.0  68.0
    2반  60.0  63.0  96.0
2학년 1반  93.0  55.0   NaN
    2반  82.0  64.0  60.0

In [ ]:
df.tail()맨 마지막 데이터 5개

언어          수리
           국     영     수
1학년 1반  70.0  72.0  68.0
    2반  60.0  63.0  96.0
2학년 1반  93.0  55.0   NaN
    2반  82.0  64.0  60.0

In [ ]:
df.dtypes

언어  국    float64
    영    float64
수리  수    float64
dtype: object

In [ ]:
df.describe() # 정보가 다 나온다

언어                    수리
               국          영          수
count   4.000000   4.000000   3.000000
mean   76.250000  63.500000  74.666667
std    14.338177   6.952218  18.903263
min    60.000000  55.000000  60.000000
25%    67.500000  61.000000  64.000000
50%    76.000000  63.500000  68.000000
75%    84.750000  66.000000  82.000000
max    93.000000  72.000000  96.000000

In [ ]:
df.isnull()

언어            수리
            국      영      수
1학년 1반  False  False  False
    2반  False  False  False
2학년 1반  False  False   True
    2반  False  False  False

In [ ]:
df.isnull().sum()

언어  국    0
    영    0
수리  수    1
dtype: int64

#<strong>값의연결</strong>

In [ ]:
a = pd.DataFrame(np.arange(1,10).reshape(3,3))
a


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
b = pd.Series(np.arange(10,40,10))
b


0    10
1    20
2    30
dtype: int64

In [ ]:
pd.concat([a,b],axis=1) #옆으로 합쳐짐

0  1  2   0
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [ ]:
pd.concat([a,b],axis=1,ignore_index=True)

0  1  2   3
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [ ]:
a.append(b,ignore_index=True)

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  20  30